# Python review

Short review about some core concepts in python exemplified by objects in the Numpy library.

- recall basic python vocabulary
- practice markdown syntax

## Libraries and packages 

**library:** is a collection of code that we can use to perform specific tasks in our programs. It can be as single file or multiple files. 

**NumPy**

- core library for numerical computin in pythin
- many of libraries use NumPy arrays as theri building blocks
- computations on NumPyobjects ar eoptimized for speed and memory usage

In [23]:
# Import NumPy with standard abbreviations np
import numpy as np
import pandas as pd

(esc + press M twice -> convert code cell to markdown cell)
## Variables 

**variable:** a name we assign to a particular object in python

In [3]:
# Example 
# Assign a small array to variable a

a = np.array([[1,1,2],[3,5,8]])

In [4]:
# View variable value
# Run variable name

a

array([[1, 1, 2],
       [3, 5, 8]])

In [5]:
# Use print to print value

print(a)

[[1 1 2]
 [3 5 8]]


In [6]:
print(a)
type(a)

[[1 1 2]
 [3 5 8]]


numpy.ndarray

In [7]:
print(a[0,0])
type(a[0,0])

1


numpy.int64

In [8]:
?print

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method

What we obtain is a **docstring**, a speecial type of comment that is used to document how a function (or a class or module) works.

Notice is that there are different types of arguments inside the funtion's paranthesis

Roughly speaking, a function has two types of arguments:



In [9]:
print('changing the default end argument of the print function', end=' ^_^')

changing the default end argument of the print function ^_^

## Attributes and methods

An object in Python has attributes and methods.

- **attributes**: a property of the object, some piece of information about it. 
- **method**: a procedure associated with an object, so it is an action where the main ingredient is the object itself. 

## Check-in

Make a diagram like that cat one, for a class 'fish'. What are its (3) attributes and (3) methods?

Example:

NumPy arrays 

In [10]:
# A 3x3 array
var = np.array([[1,2,3],[4,5,6],[7,8,9]])
var

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
# T is an example of an attribute, it returns the transpose of array

print(var.T)
print(type(var.T))

[[1 4 7]
 [2 5 8]
 [3 6 9]]
<class 'numpy.ndarray'>


In [12]:
print(var.shape)
print(type(var.shape))

(3, 3)
<class 'tuple'>


In [19]:
print(var.ndim)
print(type(var.ndim))

2
<class 'int'>


In [15]:
var.tolist()

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [16]:
var.min(axis=0)

array([1, 2, 3])

In [17]:
type(var.tolist)

builtin_function_or_method

In [18]:
type(var.min)

builtin_function_or_method

Remember, methods are **functions** associated with an object. We can confirm this!

## Exercise

1. Read the 'print' function help. What is the type of argument 'sep'? Is this a default or non-default argument? Why?

2. Create two new variables, one with the integer value 77 and another one with the string 99.

3. Use your variables to print 77%99%77 by changing the value of one of the optional arguments in 'print'.

In [20]:
num = 77
string_99 = '99'

print(num, string_99, num, sep = '%')

77%99%77


## Check-in 1

1. The integer number -999 is often used to represent mising values. Create a 'pandas.Series' named 's' with four integer values, two of which are -999. The index of this series shoujld be the letters A through D. 

2. In the pandas.Series documentation, look for the method mask(). Use this method to update between series s so that the -999 values are replaced by NA values. HINT: check the first example in the method’s documentation.

In [21]:
# code

## Check-in 2

We can access the data frame’s column names via the columns attribute. Update the column names to C1 and C2 by updating this attribute.

In [24]:
d = {'col_name_1': pd.Series(np.arange(3)),
    'col_name_2': pd.Series([3.1,3.2,3.3])}
df = pd.DataFrame(d)
df

df = df.rename(columns={'col_name_1':'C1','col_name_2':'C2'})
df

C1   C2
0   0  3.1
1   1  3.2
2   2  3.3

In [26]:
# rename
df.columns = ['C1','C2']
df

C1   C2
0   0  3.1
1   1  3.2
2   2  3.3